### ISSUE TITLE
IE MIPs generation

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#12]
Something that's been driving me crazy in my quest for optimum graphical quality :
There are cases where I just want to add MIPs to a texture, without changing the format. I've noticed if I do that with IE (autofix too), the entire texture gets recompressed. ie loss of quality.

I've gotten around this issue by using the nvcompress.exe from nvidia's texture tools. When you process eg a dxt1 with "nvcompress -bc1 filename.dds", it simply adds MIPs, no recompression. It supports DXT1, DXT5, ATI2, not V8U8. I'm sure there is a way to losslessly add MIPs to the other formats too.

What would be nice is to have the same feature in IE. Everytime you can do something losslessly, go for it :). The DDS file format is already bad enough^^.

Btw, thanks again for your work. I've been using IE a lot for ALOT 2017.

**Comment by KFreon** [comment]
Two things:
1) I can make it so that when you load a texture without mipmaps, and you tell it to generate new ones but the save format is the same, I can have it use the original texture data so the top mip doesn't lose quality.

2) Something you could do with some fiddling in cmd or bash or something: If you have two textures of the same format, one without mips, and one is the mips of the other (minus the top one), you could have it chop off the header (first 128 bytes), then just binary copy the mips to the end of the top one.

i.e. 
**Image 1**
_128 byte header
Texture (no mips)_

**Image 2** 
_128 byte header
Mipmaps of Image 1_

Then you chop off the 128 bytes of **Image 2** and copy them to the end of **Image 1** so it looks like:
**Image 1**
_128 byte header
Texture (no mips)
Mipmaps of Image 1_

That sounds complicated but I think that can be done in the cmd with the _copy_ command and the /b flag. Dunno though.
Might be best to just wait for me to stop recompressing things :P

**Comment by starkgate** [comment]
1. Makes perfect sense. Important thing is, don't process the top MIP if it is not needed.
2. Nvidia's texture tools allow you to do just that. I used nvcompress, which seems to have that behaviour automatically, but you can reproduce said behaviour with detach.exe and stitch.exe.
ie, if you have say a file.dds texture :
- Make a copy of the file : file2.dds
- Generate MIPs on file2.dds. No matter if recompression happens.
- detach.exe file2.dds. You end up with all the MIPs, separated into their own textures.
- Replace the top MIP you just extracted from file2.dds with file.dds.
- stitch.exe file.dds. Done.
Same result, a little bit more complicated to automate :).

For now, I have a script that automatically adds MIPs losslessly to all relevant textures, in a given folder. It was quite fun to write, on Linux (using nvddsinfo for format and MIP detection, and nvcompress for MIP generation).

**Comment by KFreon** [comment]
Should be fixed in the [latest release.](https://github.com/KFreon/CSharpImageLibrary/releases/tag/4.1.1)
The nVidia texture tools are handy but I found them lacking in most respects, at least for my purposes.

**Comment by starkgate** [comment]
Works beautifully, thank you !
