### ISSUE TITLE
IE 4.1.2 - NullReferenceException on bulk extract

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#22]
I tried loading a folder of 662 DDS textures in IE, checked "Use source format" and "GenerateNew" mips. No matter whether I select "Same folder as original" or add a path, I get the exception below :
![ui_project_2017-02-13_18-34-43](https://cloud.githubusercontent.com/assets/12874678/22894980/2782ad12-f21b-11e6-953b-38c033518cc6.png)

I'm also worried about the DXT1 alpha settings. There doesn't seem to be an option to just keep the alpha as is, only to either remove it or flatten the RGB+A channels. Could this be a problem or is this setting ignored in same format conversion ?

**Comment by KFreon** [comment]
A quick look at the code tells me nothing as usual...
I'll have to take a look later.

As for DXT1, ~~I think maybe that's possible? I dunno, good idea though, I don't know why I wouldn't have done that already though.~~
EDIT: Well the problem is, that would only really work if the original source was DXT1.
So the settings should be on a scale. If DXT1 is the source, pretty much any setting will keep the alpha.
