### ISSUE TITLE
Separate UI from rest of code

### ISSUE THREAD

**Issue by Ryder25** [KFreon/CSharpImageLibrary#3]
First of all, thank you for creating this library!

Can you separate the UI code from the library code?

It'd be nice to have a demo project, and a library project here on github, but I think the nuget package should just have the main image library code.

**Comment by KFreon** [comment]
Thank you! I hope it works properly :)
Seems like a sensible request. I'll see if I can find some time over the next few weeks.

**Comment by Ryder25** [comment]
Great, looking forward to the update!

It's been working quite well for my needs. (Using it to preview images in a WPF ui) 
I've noticed some crashes using your test application in certain situations, but I'll have to spend some more time investigating those before I report them.

**Comment by KFreon** [comment]
I wasn't thinking too much before, but I'm curious: Why do you want the UI separated from the rest?
I ask because I use the UI in several other projects and would rather not have two nuget packages for it, so if it's not causing any problems, I'll probably just leave it as is, I'm afraid.

EDIT: Also I'm glad someone else is using it :)

**Comment by Ryder25** [comment]
I suppose it's not too big of a problem. I just found it odd to have the UI there, especially since the output type is an executable rather than a dll, and I'm distributing a "CSharpImageLibrary.exe" with my own application.

On a side note, the code here on Github shows that it's on version 3.1.6, however it's a commit or so ahead of the nuget package with the same version.

**Comment by KFreon** [comment]
I'm bad at the whole MVVM-separate-UI-from-code thing atm, especially since sometimes it saves hundreds of lines to just throw a line or two of UI code where it "shouldn't".

I've really dropped the ball on the nuget releases. There's a bunch of stuff not in the nuget package yet. 
I'll see if I can get it updated, and definitely need to change it from exe.
Must have forgotten to change it back after testing.

**Comment by Ryder25** [comment]
Agreed. It can be such a pain sometimes to get things going with MVVM. It's a pretty steep learning curve too.

Sounds good on the updates, and changes.  I'll let you know if I find any bugs once the new version is released.

**Comment by KFreon** [comment]
Ok,[ updated to the latest stuff. ](https://github.com/KFreon/CSharpImageLibrary/releases/tag/V3.2)
Since I'm writing it as I need the bits, I'm just hoping it all still works :)

Also, as for the retargetting, I'm trying to figure out how to get a single package with multiple framework targets, so I can target low for those who have constraints, and also have the most performant package available as well.

**Comment by Ryder25** [comment]
Perfect! Looks like the parts I was using are still working as they should, and it is in a library output now.

I haven't dealt with creating nuget packages myself so I can't help you there, unfortunately.

Thanks for updating!

**Comment by KFreon** [comment]
Anytime :)
