### ISSUE TITLE
Windows 7 hangs at Debugger.Break()

### ISSUE THREAD

**Issue by Ryder25** [KFreon/CSharpImageLibrary#8]
For some reason, when working with dds files that have different height and width, the application hangs on Windows 7. (probably because WICs are used for Win 10)  After debugging, I found that this happens on these lines:

```csharp
// KFreon: If mip is too small, skip out. This happens most often with non-square textures. I think it's because the last mipmap is square instead of the same aspect.
                if (mipWidth <= 0 || mipHeight <= 0 || compressed.Position >= compressed.Length)  // Needed cos it doesn't throw when reading past the end for some reason.
                {
                    Debugger.Break();
                    break;
}
```

What's odd is that this happens even when a debugger is not attached (Both in debug and release mode when using "Start Without Debugging") It works just fine when debugging in debug mode. (hits the breakpoint as it should)

This is not limited to just this line of code, but anywhere else that Debugger.Break() is used.  I'm not really sure why this is happening since I expect these lines of code to only be functional when a debugger is attached.

On a side note, is there a simple switch to ignore using the WIC on Win 10 for testing purposes?

**Comment by KFreon** [comment]
Oh boy. Yeah that line is only supposed to be hit when running through Visual Studio. 
I'll have to keep that in mind and remove them all for the next release :(

That stuff is from the native codecs (non-WIC). I can't figure out this whole "Virtual size" deal i.e. when things are small, you're supposed to interpret them as 4x4 still. I just ignore them at that size.

In code there's a switch :)  Top of the ImageEngine class in the static constructor, you can just set WindowsCodecsAvailable to false after it checks them.
So that'll use my codecs for everything except PNG, JPG, etc. Pretty much just DDS for that release.

**Comment by Ryder25** [comment]
It may be a .NET framework bug.  I have reported it here:
https://connect.microsoft.com/VisualStudio/feedback/details/3113231/debugger-break-crashes-hangs-application-when-debugger-is-not-attached

Ignoring those mips is fine for my purposes, although if you want to display it properly, have a look at how Visual Studio opens dds files.  Once either width or height goes below 4 pixels, then it keeps the linear size at 4x4, and only fills out as many pixels as there are leftover, leaving the extras as transparent.

Thanks for the tips!

**Comment by KFreon** [comment]
There you go...
And I might look at the padding/virtual thing again :D
